import "bootstrap/dist/css/bootstrap.min.css";
import './globals.css'
import { Inter } from 'next/font/google'
<<<<<<< HEAD
import Nav from './nav.js';
import Footer from './footer.js';

=======
import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";
>>>>>>> 93e8dccb9f646884a274cd4fd7318919b1345791


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}> 
      {children}</body>
<<<<<<< HEAD
      <div><Footer/></div>
=======
>>>>>>> 93e8dccb9f646884a274cd4fd7318919b1345791
    </html>
  )
}



