import "bootstrap/dist/css/bootstrap.min.css";
import './globals.css'
import { Inter } from 'next/font/google'
import Nav from './nav.js';
import Footer from './footer.js';



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}> 
      <div><Nav/></div>
      {children}</body>
      <div><Footer/></div>
    </html>
  )
}



